### PR TITLE
Fixed weights for non-XCM related pallets

### LINKED ISSUE #138: 🐞 [Bug]: 3.2.4 Fix insufficient benchmarking for runtime pallets
Reported by SR labs.

Fix all the defaults benchmarking with actual runtime benchmarks -> weights instead of SubstrateWeights, please refer to the Glutton-Kusama parachain [12] as a best practice example.

### PR DESCRIPTION
**Pull request by KitHat**
Fixes #138 

* Generated benchmarked for all non-XCM pallets
* Fixed `runtime-benchmarks` build
* Added more pallets to `define_benchmarks` macro

### CODE REVIEW

File: runtime/src/xcm_config.rs [hunk 1]
```diff
@@ -202,8 +197,6 @@ impl pallet_xcm::Config for Runtime {
     type ExecuteXcmOrigin = EnsureXcmOrigin<RuntimeOrigin, LocalOriginToLocation>;
     type MaxLockers = MaxLockers;
     type MaxRemoteLockConsumers = MaxLockers;
-    #[cfg(feature = "runtime-benchmarks")]
-    type ReachableDest = ReachableDest;
```
Comment (ozgunozerk) [inline runtime/src/xcm_config.rs:206]: removal of this was related to fixing the runtime-benchmarks build? Any more info about this change?

Comment (KitHat) [reply runtime/src/xcm_config.rs:206]: Exactly. This change was breaking the runtime-benchmarks build
